# Site settings
title: Mehdi Khalili
email: me@mehdi-khalili.com
description: > # this means to ignore newlines until "baseurl:"
  Agile Coach, Lean Instigator, Mentor, Leader, Programmer, Presenter, Blogger
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mehdi-khalili.com" # the base hostname & protocol for your site
twitter_username: MehdiKhalili
github_username:  MKhalili

# Build settings
markdown: kramdown

# Outputting
permalink: /:title
