# Site settings
title: Mehdi Khalili
author: Mehdi Khalili
email: me@mehdi-khalili.com
disqus_short_name: mehdikhalilisblog
description: > # this means to ignore newlines until "baseurl:"
  Executive leader, mentor, change agent
disclaimer: Opinions are my own and not the views of my employer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.mehdi-khalili.com" # the base hostname & protocol for your site
twitter_username: MehdiKhalili
linkedin_username: mehdikhalili
linkedin_name: Mehdi Khalili
github_username:  MehdiK

# Build settings
markdown: kramdown

# Outputting
permalink: /:title
